theme: jekyll-theme-minimal
# Name of website
title: Massih's Git

# Short description of your site
description: I stepped into the programming world in my teens with a CASIO FX-702P programmable calculator. With a collection of built-in math function, it was a suitable tool for those who were interested in automating simple to semi-complex math problems. When the home computers became popular (for dual use of gaming and BASIC programming), my pick was a ZX-Spectrum +2, pretty much for the same trend of programming interests.

