theme: jekyll-theme-minimal
# Name of website
title: Massih's Git

# Short description of your site
description: A coding sandbox

avatar: "https://avatars2.githubusercontent.com/u/32888702?s=400&amp;u=e6013dc9169a0de37851961ab898847c821c5bff&amp;v=4"

